---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: check os family
      fail: msg="This playbook is only for macos!"
      when: (ansible_facts['distribution'] != "MacOSX")
      tags:
        - always
    - name: check os version
      fail: msg="Please update your MacOS to 11 Big Sur or later!"
      when: (ansible_distribution_version is version('11', '<'))
      tags:
        - always
    - name: setup zsh
      import_role:
        name: zsh
      tags:
        - base
        - zsh
    - name: copy dotfiles
      import_role:
        name: dotfiles
      tags:
        - base
        - dotfiles
    - name: configure vim
      import_role:
        name: vim
      tags:
        - base
        - vim
    - name: configure osx
      import_role:
        name: osx
      tags:
        - base
        - osx
    - name: configure iterm2
      import_role:
        name: iterm2
      tags:
        - base
        - iterm
        - iterm2
    - name: setup ssh key
      import_role:
        name: ssh
      tags:
        - credentials
        - ssh
    - name: setup nodejs dev env
      import_role:
        name: nodejs
      tags:
        - development
        - nodejs
