---
- hosts: localhost
  gather_facts: true
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: check os family
      fail: msg="This playbook is only for macos!"
      when: (ansible_facts['distribution'] != "MacOSX")
      tags:
        - always
    - name: check os version
      fail: msg="Please update your MacOS version to 13 Ventura or later!"
      when: (ansible_distribution_version is version('13', '<'))
      tags:
        - always
    - name: setup dotfiles
      import_role:
        name: dotfiles
      tags:
        - dotfiles
    - name: setup zsh
      import_role:
        name: zsh
      tags:
        - zsh
    - name: configure osx
      import_role:
        name: osx
      tags:
        - osx
    - name: setup nodejs
      import_role:
        name: nodejs
      tags:
        - nodejs
