- name: download dotfiles repo
  git:
    repo: "git@github.com:chaudhryjunaid/rcfiles.git"
    dest: "{{ansible_user_dir}}/rcfiles"
- name: link dotfiles
  shell: $HOME/rcfiles/setup.sh
  args:
    creates: "{{ansible_user_dir}}/.zshrc.custom"