- name: ensure fonts are installed.
  get_url:
    url: "{{ item.url }}"
    dest: "~/Library/Fonts"
  with_items: "{{ iterm2_fonts }}"
  when: iterm2_fonts is defined

# - name: ensure preferences are loaded from a custom folder
#   osx_defaults:
#     domain: com.googlecode.iterm2
#     key: PrefsCustomFolder
#     type: string
#     value: '{{ iterm2_preferences_custom_folder }}'
#   when: iterm2_preferences_custom_folder is defined and iterm2_preferences_custom_folder

# - name: create iterm prefs folder
#   file:
#     path: "{{ iterm2_preferences_custom_folder }}"
#     state: directory

# - name: copy preferences file
#   copy:
#     src: "com.googlecode.iterm2.plist"
#     dest: "{{ iterm2_preferences_custom_folder }}/com.googlecode.iterm2.plist"
#   when: iterm2_preferences_custom_folder is defined and iterm2_preferences_custom_folder
